### ISSUE TITLE
Apps loading way too slow

### ISSUE THREAD

**Issue by notsceptor** [albu-razvan/Stario#42]
**Describe the bug**
Apps take a good 1-5 seconds to appear on the home screen / application drawer, meaning I can't click on any of them until they're all loaded. This doesn't happen to me on any other launcher, which is weird because other launchers are normally less minimal, yet they can still load faster.

**To Reproduce**
Steps to reproduce:
1. Go to your home screen
2. Wait for apps to load

**Expected behaviour**
Apps load fast just like the default / other app launchers

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A15
 - OS: One UI 6.1 / Android 14

**Comment by Selemba1000** [comment]
Does that happen every time when opening the drawer or just in the first start. Because it seems to be caching correctly on my device. If it is just on the first start I don't really know what could be the problem, but if it is on every open I would guess it is not caching correctly. Maybe look into caching and how to keep it persistent.

**Comment by albu-razvan** [comment]
Might be a cold start issue related to #22 #36 and #43. Caching seems to work fine. Will come back to this once said issues are closed.

**Comment by albu-razvan** [comment]
I couldn't find any way to improve the inflation speed on a cold start. However, #49 might contribute to the overall perceived efficiency of the launcher in these situations.
